### ISSUE TITLE
MongoError: connect ECONNREFUSED

### ISSUE THREAD

**Issue by JesseVS** [BastienM/rocketchat-kubernetes#2]
Hi Bastien,

I get the following error when I follow your tutorial:
```
$ kubectl -n rocketchat logs rocketchat-app-658557f9c8-ppzjp

/app/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^
MongoError: failed to connect to server [mongo-1.mongo:27017] on first connect [MongoError: connect ECONNREFUSED 10.244.47.12:27017]
    at Pool.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
```
The mongo pods are up:
```
NAME                              READY     STATUS             RESTARTS   AGE
mongo-0                           2/2       Running            0          3m
mongo-1                           2/2       Running            0          3m
mongo-2                           2/2       Running            0          3m
rocketchat-app-658557f9c8-ppzjp   0/1       CrashLoopBackOff   4          3m
```
Am I doing something wrong?

**Comment by BastienM** [comment]
Hi @nedbase-jesse,

Mongo latest image must have made some changes to how `mongod` is started. Resulting in the daemon not accepting external connections : 
```
** WARNING: This server is bound to localhost.
**          Remote systems will be unable to connect to this server.
**          Start the server with --bind_ip <address> to specify which IP
**          addresses it should serve responses from, or with --bind_ip_all to
**          bind to all interfaces. If this behavior is desired, start the
**          server with --bind_ip 127.0.0.1 to disable this warning.
```

I will try fixing this issue asap, thanks for reporting it 👍
